version: '3.9'

services:
  postgres:
    image: postgres:16

    container_name: triphoria-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: triphoria
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./indexes.sql:/docker-entrypoint-initdb.d/indexes.sql

volumes:
  postgres_data:
